@baseUrl = http://localhost:3000

GET {{baseUrl}}

###
GET {{baseUrl}}/conceitos-automaticos

### Retorna todos os recados
GET {{baseUrl}}/recados

### Retorna somente um recado
GET {{baseUrl}}/recados/18

### Cria um novo recado
POST {{baseUrl}}/recados
Content-Type: application/json

{
   "message": "Novo Recado dois"
}

### Atualiza um recado
PUT {{baseUrl}}/recados/14
Content-Type: application/json

{
   "message": "Atualiza o Recado"
}

### Deleta um recado
DELETE {{baseUrl}}/recados/19